using BusStop.Core.CountryAggregate;

namespace BusStop.IntegrationTests.Data;

public class CountryConfigurationTests : IntegrationTestBase
{
    [Fact]
    public async Task AddCountry_PersistsCorrectly()
    {
        var country = Country.Create("TestCountry", "TC");
        DbContext.Countries.Add(country);
        await DbContext.SaveChangesAsync(TestContext.Current.CancellationToken);

        var saved = await DbContext.Countries.FirstOrDefaultAsync(TestContext.Current.CancellationToken);
        saved.ShouldNotBeNull();
        saved.Name.ShouldBe("TestCountry");
        saved.IsoCode.ShouldBe("TC");
        saved.Id.ShouldBeGreaterThan(0);
    }

    [Fact]
    public async Task CountryId_IsAutoGenerated()
    {
        var country1 = Country.Create("Country1", "C1");
        var country2 = Country.Create("Country2", "C2");
        DbContext.Countries.AddRange(country1, country2);
        await DbContext.SaveChangesAsync(TestContext.Current.CancellationToken);

        country1.Id.ShouldBeGreaterThan(0);
        country2.Id.ShouldBeGreaterThan(0);
        country1.Id.ShouldNotBe(country2.Id);
    }
}
